[package]
name = "tib"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
eyre = "0.6.14"
libc = "0.2.189"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.5"

[lints.clippy]
# UM, ACTUALLY
pedantic = { level = "deny", priority = -1 }
# DEVELOPING LINTS
nursery = { level = "deny", priority = -1 }
# DENY PANICS
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
